(Concept Bat@Man (Property (flight 0.9) (echolocation 0.9) (nocturnality 0.8) (intelligence 0.3) (physical-strength 0.2) (reasoning 0.3) (symbolism 0.8) (iconography 0.7)))
(Concept Bat@Man (Property (flight 0.9) (echolocation 0.9) (nocturnality 0.8) (intelligence 0.3) (physical-strength 0.2) (reasoning 0.3) (symbolism 0.8) (iconography 0.7)))
(Concept Man@Bat (Property (flight 0.0) (echolocation 0.0) (nocturnality 0.2) (intelligence 0.9) (physical-strength 0.8) (reasoning 0.9) (symbolism 0.4) (iconography 0.3)))
