(Concept history-intelligence-tools-language
  (HabitCount 1)
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (language (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-strategy
  (HabitCount 1)
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (strategy (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-engineering
  (HabitCount 1)
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (engineering (WorldSpecSet ()) 1.0))))

(Concept history-intelligence-tools-logic
  (HabitCount 1)
  (V-predicate
    (Property
      (intelligence (WorldSpecSet ()) 1.0)
      (tools (WorldSpecSet ()) 1.0)
      (logic (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-balance
  (HabitCount 1)
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (balance (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-vertical
  (HabitCount 1)
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (vertical (WorldSpecSet ()) 1.0))))

(Concept history-climbing-agility-ropes
  (HabitCount 1)
  (V-predicate
    (Property
      (climbing (WorldSpecSet ()) 1.0)
      (agility (WorldSpecSet ()) 1.0)
      (ropes (WorldSpecSet ()) 1.0))))

(Concept history-webs-insects-sticky
  (HabitCount 1)
  (V-predicate
    (Property
      (webs (WorldSpecSet ()) 1.0)
      (insects (WorldSpecSet ()) 1.0)
      (sticky (WorldSpecSet ()) 1.0))))

(Concept habit-access_internet-carrying_groceries
  (HabitCount 2)
  (V-predicate
    (Property
      (access_internet (WorldSpecSet ()) 1.0)
      (carrying_groceries (WorldSpecSet ()) 1.0))))
