import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from libs.colimit import compute_colimit

def generate():
    # 1. Define Inputs Directly
    spec_house = "(Concept House (spec (sorts (Medium)) (ops ((: h House))) (axioms (on h Land))))"
    spec_boat = "(Concept Boat (spec (sorts (Medium)) (ops ((: b Boat))) (axioms (on b Water))))"
    spec_generic = "(Concept Generic (spec (sorts (Medium)) (ops ((: x Entity))) (axioms (on x Medium))))"
    
    # 2. Define Maps 
    map_a = {"sorts": {"Medium": "Medium"}, "ops": {"x": "h"}, "preds": {"on": "on"}}
    map_b = {"sorts": {"Medium": "Water", "Entity": "Boat"}, "ops": {"x": "b"}, "preds": {'on': 'on'}}

    # 3. Compute the Colimit
    print("Generating Blend...")
    blend_code = compute_colimit(spec_house, spec_boat, spec_generic, map_a, map_b)

    # 4. SAVING THE OUTPUT 
    output_path = os.path.join(os.path.dirname(__file__), "blend_output.metta")
    with open(output_path, "w") as f:
        f.write("; This file is auto-generated by colimit.py\n")
        f.write(blend_code)
    
    print(f"Success! Blend saved to: {output_path}")

if __name__ == "__main__":
    generate()