import sys
import os
import json

# 1. SETUP PATHS
# Add the current directory to sys.path so we can import 'libs'
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

try:
    from libs.colimit import compute_colimit
    print(" Successfully imported compute_colimit.")
except ImportError as e:
    print(f" Import Error: {e}")
    print("   Ensure 'tests/libs/colimit.py' and 'tests/libs/__init__.py' exist.")
    sys.exit(1)

# 2. DEFINE MOCK DATA
# These represent the Algebraic Specifications normally generated by the LLM.

# Spec A: House
spec_a = """
(Concept House
 (spec
  (sorts (Wall Window Roof))
  (ops ((: build Wall) (: open Window)))
  (preds ((keeps_warm Wall)))
  (axioms ((keeps_warm (build))))
 )
)
"""

# Spec B: Boat
spec_b = """
(Concept Boat
 (spec
  (sorts (Hull Porthole Sail))
  (ops ((: float Hull) (: open Porthole)))
  (preds ((keeps_dry Hull)))
  (axioms ((keeps_dry (float))))
 )
)
"""

# Spec G: Generic Container (The Shared Structure)
spec_g = """
(Concept Generic
 (spec
  (sorts (Boundary Aperture))
  (ops ((: make Boundary) (: open Aperture)))
  (preds ((protects Boundary)))
  (axioms ((protects (make))))
 )
)
"""

# 3. DEFINE MAPPINGS (Morphisms)
# Maps from Generic -> Specific
# Note: "Aperture" maps to "Window" in House, and "Porthole" in Boat.
#       This forces the system to merge Window and Porthole into one concept.

map_a = {
    "sorts": {"Boundary": "Wall", "Aperture": "Window"},
    "ops": {"make": "build", "open": "open"},
    "preds": {"protects": "keeps_warm"}
}

map_b = {
    "sorts": {"Boundary": "Hull", "Aperture": "Porthole"},
    "ops": {"make": "float", "open": "open"},
    "preds": {"protects": "keeps_dry"}
}

# 4. RUN THE TEST
print("\n TESTING COLIMIT ENGINE...")
print("-" * 60)

try:
    # The engine should merge 'Wall' and 'Hull' -> 'Wall_Hull' (or similar)
    # And 'Window' and 'Porthole' -> 'Window_Porthole'
    result = compute_colimit(spec_a, spec_b, spec_g, map_a, map_b)
    
    print("RESULT GENERATED:\n")
    print(result)
    
    # 5. VERIFICATION
    if "Wall_Hull" in result or "Hull_Wall" in result:
        print("\nSUCCESS: 'Wall' and 'Hull' were successfully unified!")
    elif "Window_Porthole" in result or "Porthole_Window" in result:
        print("\nSUCCESS: 'Window' and 'Porthole' were successfully unified!")
    else:
        print("\n WARNING: Unification might have failed. Check output above.")

except Exception as e:
    print(f"\n EXECUTION FAILED: {e}")